swagger: '2.0'
info:
  title: MbaaS API
  description: Endpoints For App Import and Export
  version: "1.0.0"
schemes:
  - https
basePath: /api/mbaas/

produces:
  - application/json

parameters:
  domain:
    name: domain
    in: path
    description: the domain of the application
    type: string
    required: true
  environment:
    name: environment
    in: path
    description: the environment of the application
    type: string
    required: true
  appid:
    name: appid
    in: path
    description: the unique id of the application
    type: string
    required: true
  job_id:
    name: job_id
    in: path
    description: id of the export job to download the data from
    type: string
    required: true
paths:
  "/{domain}/{environment}/{appid}/data/export":
    get:
      description: List export operations
      parameters:
        - $ref: "#/parameters/domain"
        - $ref: "#/parameters/environment"
        - $ref: "#/parameters/appid"
      responses:
        200:
          description: List of export operations, includes both ongoing operations and historical data
          schema:
            type: array
            items:
              $ref: '#/definitions/ExportJob'
        401:
          description: Authentication Invalid
      tags:
        - export
    post:
      description: Create a new export job
      parameters:
        - $ref: "#/parameters/domain"
        - $ref: "#/parameters/environment"
        - $ref: "#/parameters/appid"
      responses:
        200:
          description: New job created successfully
          schema:
            $ref: '#/definitions/ExportJob'
        401:
          description: Authentication Invalid
        500:
          description: Error creating job

  "/{domain}/{environment}/{appid}/data/export/{job_id}":
    post:
      description: Create download token+url for generated file
      parameters:
        - $ref: "#/parameters/domain"
        - $ref: "#/parameters/environment"
        - $ref: "#/parameters/appid"
        - $ref: "#/parameters/job_id"
      responses:
        200:
          description: Token generation successful
          schema:
            properties:
              url: string
            description: Download URL for the related file, including single-use token
        401:
          description: Authentication Invalid
        404:
          description:
            Job not found or in invalid state
            (i.e. not finished successfully and with file available)
      tags:
        - export
    get:
      description: Details of an export operation
      parameters:
        - $ref: "#/parameters/domain"
        - $ref: "#/parameters/environment"
        - $ref: "#/parameters/appid"
        - $ref: "#/parameters/job_id"
      responses:
        200:
          description: Details of a single export operation
          schema:
            $ref: '#/definitions/ExportJob'
        404:
          description: job_id not found
        401:
          description: Authentication Invalid
      tags:
        - export
definitions:
  ExportJob:
    properties:
      "_id":
        type: string
      appid:
        type: string
      environment:
        type: string
      domain:
        type: string
      status:
        type: string
      step:
        type: number
      totalSteps:
        type: number
      fileSize:
        type: number
      fileDeleted:
        type: string
      filePath:
        type: string
      fileId:
        type: string
      progress:
        type: object
      created:
        type: date
      modified:
        type: date