
var validation = [
  "fhmbaas.port",
  "mongo.enabled",
  "mongo.host",
  "mongo.port",
  "mongo.name",
  "fhditch.host",
  "fhditch.port",
  "fhditch.protocol",
  "fhdfc.dynofarm",
  "fhdfc.username",
  "fhdfc._password",
  "fhdfc.loglevel",
  "fhdfc.cache_timeout",
  "fhamqp.enabled",
  "fhamqp.max_connection_retry",
  "fhamqp.nodes",
  "fhamqp.ssl",
  "fhamqp.vhosts",
  "fhamqp.vhosts.events",
  "fhamqp.vhosts.events.name",
  "fhamqp.vhosts.events.user",
  "fhamqp.vhosts.events.password",
  "fhamqp.app",
  "fhamqp.app.enabled",
  "fhmessaging.enabled",
  "fhmessaging.host",
  "fhmessaging.protocol",
  "fhmessaging.port",
  "fhmessaging.path",
  "fhmessaging.cluster",
  "fhmessaging.realtime",
  "fhmessaging.files",
  "fhmessaging.files.recovery_file",
  "fhmessaging.files.backup_file",
  "fhstats.enabled",
  "fhstats.host",
  "fhstats.port",
  "fhstats.protocol"
]

module.exports = validation;
